### ISSUE TITLE
Support multiple monitors / extended desktop

### ISSUE THREAD

**Issue by objorke** [objorke/UsageStats#3]
**This issue was imported from [CodePlex](http://UsageStats.codeplex.com/workitem/992)**

**[tophee](http://www.codeplex.com/site/users/view/tophee)** wrote 2012-11-09 at 11:04
Add support for two (or possibly more) monitors (extended desktop) 

Currently, the tracemaps only include one of my two monitiors (the primary one) and all my click- and double click maps are empty (except for the date). Not sure if this is connected with the extended desktop or a seperate issue, though.

**Comment by sadortun** [comment]
Got something working ! PR Comming soon !

![image](https://cloud.githubusercontent.com/assets/794449/14765306/92e52e54-09aa-11e6-9e5f-a44d479e03b3.png)
