### ISSUE TITLE
Mouse handler stop recording after a while

### ISSUE THREAD

**Issue by sadortun** [objorke/UsageStats#8]
After a while, the mouse hook stop working.

Keyboard hook is fine, and mouse movement is also OK

Potential cause :
http://stackoverflow.com/questions/2655278/what-can-cause-windows-to-unhook-a-low-level-global-keyboard-hook

**Comment by objorke** [comment]
Thanks for the link to a possible solution!

**Comment by sadortun** [comment]
Have you notice this before ?   I am running on Win10

**Comment by objorke** [comment]
I have not tested the UsageStats program recently. I have probably not used it on Windows 10...
But I have been running the TimeRecorder program constantly the last years, but that one doesn´t use the hooks, I think.

**Comment by sadortun** [comment]
Issue should be fixed. UsageStats is running for a full 3 days without problems.

**Comment by sadortun** [comment]
Ok, i am prety sure i found the issue. The mouse callback can take too much time and it get kicked from the hook list. Calling it async seems to fix it.

```c#
   System.Windows.Application.Current.Dispatcher.BeginInvoke(new Action(() =>
                    {
                        _handler(wParam, lParam);
                    }));
```
